### ISSUE TITLE
Microsoft.JSInterop.JSException: element.addEventListener is not a function

### ISSUE THREAD

**Issue by Titanitus** [microsoft/fluentui-blazor#2253]
# 🐛 Bug Report

After upgrade Microsoft.FluentUI.AspNetCoreComponents from version 4.7.2 to 4.8.0 this error apears openning the home page:
Microsoft.JSInterop.JSException: element.addEventListener is not a function TypeError: element.addEventListener is not a function at Module.RegisterKeyCode (http://localhost:5000/_content/Microsoft.FluentUI.AspNetCore.Components/Components/KeyCode/FluentKeyCode.razor.js:47:17) at http://localhost:5000/_framework/blazor.web.js:1:3244 at new Promise (<anonymous>) at y.beginInvokeJSFromDotNet (http://localhost:5000/_framework/blazor.web.js:1:3201) at gn._invokeClientMethod (http://localhost:5000/_framework/blazor.web.js:1:62841) at gn._processIncomingData (http://localhost:5000/_framework/blazor.web.js:1:60316) at connection.onreceive (http://localhost:5000/_framework/blazor.web.js:1:53957) at i.onmessage (http://localhost:5000/framework/blazor.web.js:1:82102) at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args) at Microsoft.FluentUI.AspNetCore.Components.FluentKeyCode.OnAfterRenderAsync(Boolean firstRender) in //src/Core/Components/KeyCode/FluentKeyCode.razor.cs:line 126 at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

## 💻 Repro or Code Sample

Downgrade to Microsoft.FluentUI.AspNetCoreComponents from version 4.7.2 - works
Downgrade to Microsoft.FluentUI.AspNetCoreComponents from version 4.8.0 - do not works

## 🌍 Your Environment

* OS & Device: Windows
* Browser Microsoft Edge
* .NET and Fluent UI Blazor library Version 8.0.302 and 4.8.0

**Comment by Titanitus** [comment]
Overwatched the same issue is opened ...
